baseURL = 'https://blog.linuxjava7.dev/'
languageCode = 'en-gb'
title = "LinuxJava7's Blog"

theme = "tale"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
author = { name = "LinuxJava7" }
