baseURL = 'https://blog.linuxjava7.dev/'
languageCode = 'en-gb'
title = "LinuxJava7's Blog"

theme = "PaperMod"

[caches]
[caches.images]
dir = ':cacheDir/images'

[params.homeInfoParams]
Title = "Hi! This is my blog."
Content = "I write stuff sometimes."

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@linuxjava7"

[[params.socialIcons]]
name = "github"
url = "https://github.com/LinuxJava7/"

[[menu.main]]
name = "Home"
url = "https://linuxjava7.dev/"
